---

directories:
  - "{{ consul_config_dir }}"
  - "{{ consul_data_dir }}"
  - "{{ consul_logs_dir }}"
  - "{{ consul_scripts_dir }}"

files: [
  { src: "mem.sh", dest: "/data/consul/scripts/mem.sh", mode: "0755" },
  { src: "disk.sh", dest: "/data/consul/scripts/disk.sh", mode: "0755" }
]

templates: [
  { src: "consul.conf.j2", dest: "/etc/init/consul.conf", mode: "0644" },
  { src: "redeploy_service.sh.j2", dest: "/data/consul/scripts/redeploy_service.sh", mode: "0755" },
  { src: "store_deploy.sh.j2", dest: "/data/consul/scripts/store_deploy.sh", mode: "0755" }
]
consul_version: 0.6.3
consul_sha256sum: b0532c61fec4a4f6d130c893fd8954ec007a6ad93effbe283a39224ed237e250

consul_template_version: 0.12.2
consul_template_sha256sum: a8780f365bf5bfad47272e4682636084a7475ce74b336cdca87c48a06dd8a193

consul_webui_version: 0.6.3
consul_webui_sha256sum: 93bbb300cacfe8de90fb3bd5ede7d37ae6ce014898edc520b9c96a676b2bbb72

consul_download_dir: /root
consul_install_dir: /usr/local/bin
consul_config_dir: /etc/consul.d
consul_data_dir: /data/consul/data
consul_logs_dir: /data/consul/logs
consul_webui_dir: /data/consul/ui
consul_scripts_dir: /data/consul/scripts

consul_pid_file: /var/run/consul.pid
consul_log_file: consul.log

consul_server: false
consul_webui: false

consul_user: consul
consul_group: consul
consul_service_name: consul

consul_ui_server_port: 80
consul_ui_auth_user_file: /etc/htpasswd/consul
consul_ui_server_name: "{{ ansible_fqdn }}"
consul_ui_require_auth: true

consul_gomaxprocs: 1

consul_acl_datacenter: ''
consul_acl_default_policy: allow
consul_acl_down_policy: extend-cache
consul_acl_master_token: ''
consul_acl_token: ''
consul_acl_ttl: 30s
consul_addresses_dns: "{{ consul_client_addr }}"
consul_addresses_http: "{{ consul_client_addr }}"
consul_addresses_https: "{{ consul_client_addr }}"
consul_addresses_rpc: "{{ consul_client_addr }}"
consul_advertise_addr: ''
consul_advertise_addr_wan: ''
consul_atlas_acl_token: ''
consul_atlas_infrastructure: ''
consul_atlas_join: false
consul_atlas_token: ''
consul_bind_addr: 0.0.0.0
consul_bootstrap_expect: 2
consul_ca_file: ''
consul_cert_file: ''
consul_check_update_interval: 5m
consul_client_addr: 0.0.0.0
consul_datacenter: dc1
consul_disable_anonymous_signature: false
consul_disable_remote_exec: false
consul_disable_update_check: false
consul_dns_config_allow_stale: false
consul_dns_config_max_stale: 5s
consul_dns_node_ttl: 0s
consul_dns_service_ttl: ''
consul_dns_enable_truncate: false
consul_dns_only_passing: false
consul_domain: ''
consul_enable_debug: false
consul_enable_syslog: false
consul_encrypt: ''
consul_http_api_response_headers: {}
consul_key_file: ''
consul_leave_on_terminate: false
consul_log_level: info
consul_node_name: ''
consul_ports_dns: 8600
consul_ports_http: 8500
consul_ports_https: -1
consul_ports_rpc: 8400
consul_ports_serf_lan: 8301
consul_ports_serf_wan: 8302
consul_ports_server: 8300
consul_protocol: ''
consul_recursors: []
consul_rejoin_after_leave: false
consul_retry_interval: 30s
consul_retry_interval_wan: 30s
consul_retry_join: []
consul_retry_join_wan: []
consul_server_name: ''
consul_session_ttl_min: 10s
consul_skip_leave_on_interrupt: false
consul_start_join: []
consul_start_join_wan: []
consul_statsd_addr: ''
consul_statsite_addr: ''
consul_statsite_prefix: consul
consul_syslog_facility: LOCAL0
consul_verify_incoming: false
consul_verify_outgoing: false
consul_verify_server_hostname: false
