---
# tasks file for vault

- name: Install libcap2-bin
  apt: name=libcap2-bin state=latest

- name: Create Vault group
  group: name={{ vault_group }} system=yes state=present
  tags: vault

- name: Create Vault user
  user: >
    name={{ vault_user }}
    shell=/bin/false
    createhome=no
    group={{ vault_group }}
    system=yes
    state=present
  tags: vault

- name: Download Vault
  get_url: >
    url={{ vault_url }}
    dest={{ vault_download_dir }}/vault.zip
    sha256sum={{ vault_sha256sum }}
  tags: vault

- name: Unzip Vault to installation directory
  command: unzip {{ vault_download_dir }}/vault.zip -d {{ vault_install_dir }}
  args:
    creates: "{{ vault_install_dir }}/vault"
  tags: vault

- name: Create Vault configuration directory
  file: >
    path={{ vault_config_dir }}
    owner=root
    group=root
    mode=0755
    state=directory
  when: consul_server
  tags: vault

- name: Create Vault upstart configuration
  template: >
    src=vault.conf.j2
    dest=/etc/init/vault.conf
    owner=root
    group=root
    mode=0644
  notify: restart vault
  when: consul_server
  tags: vault

- name: Create Vault configuration file
  template: >
    src=vault.hcl.j2
    dest={{ vault_config_dir }}/vault.hcl
    owner=root
    group=vault
    mode=0640
  notify: restart vault
  when: consul_server
  tags: vault

- name: Give vault access to mlock syscall
  capabilities: >
    path={{ vault_install_dir }}/vault
    capability='cap_ipc_lock=+ep'
    state=present

- name: Ensure Vault service is started and enabled on boot
  service: name={{ vault_service_name }} state=started enabled=yes
  tags: vault
  when: consul_server

- name: Set vault addr
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: 'VAULT_ADDR=".*"'
    line: 'VAULT_ADDR="{{vault_scheme}}{{vault_listener_tcp_address}}"'

- name: Register vault service
  consul:
    service_name: vault
    service_port: 8200
    tags: vault
  when: consul_server
  tags: vault